version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://myusername:mypassword@db:5432/autodidact
      - BIND_IP=0.0.0.0
      - BIND_PORT=5000
    depends_on:
      - db
    restart: always
    volumes:
      - ./web:/app

  db:
    image: postgres:17.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=autodidact
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
