apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.namespace }}
spec:
  acme:
    email: {{ .Values.certManagerEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.namespace }}
    solvers:
      - http01:
          ingress:
            class: nginx
