apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.cognito.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  userPoolClientSecret: {{ .Values.auth.cognito.secret.userPoolClientSecret | quote }}
