apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.flask.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  flaskAppSecret: {{ .Values.flask.secret.flaskAppSecret | quote }}
