apiVersion: apps/v1
kind: StatefulSet
metadata: { name: postgres, namespace: {{ .Values.namespace }} }
spec:
  serviceName: postgres
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - { name: POSTGRES_USER, valueFrom: { secretKeyRef: { name: postgres-secret, key: user } } }
            - { name: POSTGRES_PASSWORD, valueFrom: { secretKeyRef: { name: postgres-secret, key: pass } } }
          ports: [ { containerPort: 5432 } ]
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgresdb
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: [ ReadWriteOnce ]
        resources: { requests: { storage: 5Gi } }
---
apiVersion: v1
kind: Service
metadata: { name: postgres, namespace: {{ .Values.namespace }} }
spec:
  ports: [ { port: 5432 } ]
  selector: { app: postgres }
